# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA'

# Step 3: Configure build options to fix the logging error
options:
  logging: CLOUD_LOGGING_ONLY
