# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'designmate-app' # Your service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # IMPORTANT: Please change this to your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Push the image to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/designmate-app:$COMMIT_SHA'

# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
